# Generated by Django 5.0.2 on 2024-02-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0003_alter_video_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='is_preview',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
