# Generated by Django 5.0.2 on 2024-02-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0004_rename_is_preview_chapter_paid_alter_answers_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='paid',
            new_name='is_preview',
        ),
    ]
