# Generated by Django 5.0.2 on 2024-02-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0005_rename_paid_chapter_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
